services:
  - type: web
    name: mizan
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: AUTH_SECRET
        sync: false